version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server
    networks:
      - mynetwork
    
  app:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - mynetwork 

networks:
  mynetwork: